// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACA7FirbsdHd11duH3pxweGOPvdEflPZA',
    appId: '1:622247414004:web:8faf15e511c629363d76a1',
    messagingSenderId: '622247414004',
    projectId: 'tem-upload-file',
    authDomain: 'tem-upload-file.firebaseapp.com',
    storageBucket: 'tem-upload-file.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmO2D9L_UoXzD05BOLNKW0bIQpTFanvj4',
    appId: '1:622247414004:android:69361185f27183d03d76a1',
    messagingSenderId: '622247414004',
    projectId: 'tem-upload-file',
    storageBucket: 'tem-upload-file.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp5S9DGqQFR7moDdWmlThK5mmvsdnPfDs',
    appId: '1:622247414004:ios:23a6cdb4a03bb8533d76a1',
    messagingSenderId: '622247414004',
    projectId: 'tem-upload-file',
    storageBucket: 'tem-upload-file.appspot.com',
    iosBundleId: 'com.example.p3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp5S9DGqQFR7moDdWmlThK5mmvsdnPfDs',
    appId: '1:622247414004:ios:7c6de8dca54dd9e03d76a1',
    messagingSenderId: '622247414004',
    projectId: 'tem-upload-file',
    storageBucket: 'tem-upload-file.appspot.com',
    iosBundleId: 'com.example.p3.RunnerTests',
  );
}
